### ISSUE TITLE
Could you please file a .tar.gz release?

### ISSUE THREAD

**Issue by onkelbeh** [jesserockz/python-iglo#1]
Hi,

I would like to use your integration in my [Gentoo Overlay for Home Assistant](https://github.com/onkelbeh/HomeAssistantRepository).
Therefor I need a release file in tar.gz format.
Home Assistant currently requires: `iglo==1.2.7`
This one exists at Pypi, but only in wheel format, cannot use this.
On [Github](https://github.com/jesserockz/python-iglo) i can only find `1.2.5`
Added this one today with https://github.com/onkelbeh/HomeAssistantRepository/commit/432efbf68397649336271aafb1fb00ab071b93f5
A release on Github would be OK, but a Pypi tar.gz release **would be preferred**, because this could take use of Gentoo's mirror system.

Thanks
 \B.

**Comment by onkelbeh** [comment]
fixed it preliminary with a [fork](https://github.com/onkelbeh/python-iglo/tree/v1.2.7).

**Comment by jesserockz** [comment]
Sorry, did not see this. I have created a tag for v1.2.7.
I don't use this anymore but if it is still on my computer I will attempt to push a tar to pypi.

If you have these lights you should look at flashing them with alternative firmware. I use mine with esphome with only a gain in features including ir remote.

**Comment by onkelbeh** [comment]
Thanks a lot, I don't have any of these, i just wanted to complete all listed components for Gentoo Linux:
https://github.com/onkelbeh/HomeAssistantRepository

ESPHome is great.

**Comment by jesserockz** [comment]
No problem. Yeah I realised that after when I saw your request on my other repo too.
